services:
  rabbitmq:
    container_name: ddev-${DDEV_SITENAME}-rabbitmq
    hostname: ${DDEV_SITENAME}-rabbitmq
    image: rabbitmq:3.8-management-alpine
    expose:
      - "15672"
      - "5672"
    environment:
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      VIRTUAL_HOST: $DDEV_HOSTNAME
      HTTP_EXPOSE: 15672:15672
      HTTPS_EXPOSE: 15671:15672
    labels:
      com.ddev.approot: ${DDEV_APPROOT}
      com.ddev.site-name: ${DDEV_SITENAME}
  web:
    links:
      - rabbitmq:rabbitmq

volumes:
  rabbitmq:
